version: "3.7"
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"

  discord-bot:
    build: .
    container_name: discord_bot
    depends_on:
      - "dynamodb-local"
    ports:
      - "8080:8080"
    links:
      - "dynamodb-local"
    environment:
      - AWS_ACCESS_KEY_ID="DO-NOT-PUT-A-REAL-KEY-HERE"
      - AWS_SECRET_ACCESS_KEY="DO-NOT-PUT-A-REAL-KEY-HERE"
      - AWS_REGION="us-east-1"
    volumes:
      - ./:/the_oracle
    entrypoint: ["/bin/bash"]
    tty: true
